# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: COSMO Consult inofficial Blogs
email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#twitter_username: username
#github_username: daniel-krueger
minimal_mistakes_skin: "contrast" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
search: true
locale: en
# posts in draft are not shown
show_drafts: false
# Explanation for baseurl:
# https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
baseurl: /dkr_blog_test

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
logo: "/assets/images/layout/favicon_cc.ico"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - run_serve.bat
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

#author: default_author

footer:
  links:
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

collections:
  authors:
    output: true
defaults:
# default 
  - scope:
      path: ""
    values:
      sidebar:
        nav: "docs"
  - scope:
      path: "_authors"
      type: "authors"
    values:
      author_profile: true
      layout: "single"
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 150
      comments: true
      share: true
      related: true
      show_date: true
      permalink: /posts/:year/:month/:day/:slug
      sidebar:
        nav: "docs"
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:  
      layout: single
      show_date: true
      author_profile: true      

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
author_archive:
  type: liquid
  path: /authors/